### ISSUE TITLE
"Failed to access axc db" and "There was an error encrypting the message" errors

### ISSUE THREAD

**Issue by thegreatestminer** [gkdr/lurch#132]
Environment is Raspberry Pi 3 Model B+, Pidgin 2.12.0 (libpurple 2.12.0), built lurch on commit 3f74880. Local server running prosody-0.10 1nightly500-1~stretch. (armhf, prosody.im apt repo)

I'm getting the same error as some other people, but I'm getting a different debug error message. This is the log when I try sending a message.

Chatbox message:

```
(08:07:28 AM) There was an error encrypting the message and it was not sent. You can try again, or try to find the problem by looking at the debug log.
```

Debug log:

```
(08:07:28) lurch: lurch_message_encrypt_im: failed to get device id (-1)
(08:07:28) g_log: xmlnode_to_str_helper: assertion 'node != NULL' failed
(08:07:28) g_log: jabber_send_raw: assertion 'data != NULL' failed
(08:07:28) jabber: Sending (ssl) (pi2@192.168.2.1/cafcefa4-f890-4671-a020-969084a8f188): <message type='chat' id='purpleec71dd6c' to='ztg@192.168.2.1'><active xmlns='http://jabber.org/protocol/chatstates'/></message>
(08:07:28) gstreamer: Unable to prepare device.
```

There's no error that displays in the debug log when running any `/lurch` command. There is an error in the chatbox though;

```
Failed to access axc db /home/pi/.purple/pi2@192.168.2.1_axc_db.sqlite. Does the path seem correct?
```

Sure enough, there does exist a `pi2@192.168.2.1_axc_db.sqlite` file located in that directory.
![image](https://user-images.githubusercontent.com/19188146/54031871-f3e37b80-417d-11e9-8614-c32d4ab785f3.png)

As a final note, there was a warning during the build process, being:

```
src/axc.c:28:16: warning: struct has no members [-Wpedantic]
 typedef struct axc_mutexes {
                ^~~~~~~~~~~
```

**Comment by gkdr** [comment]
Hi!

Is this a fresh checkout or were you running it before? The _libsignal-protocol-c_ dependency got a major bump with that release and if you have anything left on your system it might not work.

In your screenshot I also see that you seem to be using OTR - IIRC there are issues using the two plugins together. Does deactivating the OTR plugin fix the issue for you? (Not claiming that's a solution...)

The warning is "okay" - I implemented all the interfaces required by _libsignal-protocol-c_, but since _libpurple_ is singlethreaded, I remove the code by preprocessor, which was necessary for Windows compatibility (iirc).

**Comment by thegreatestminer** [comment]
Sorry for the late reply. What do you mean by checkout? (I'm not familiar with git terms and the likes) If you mean if it's a fresh build of lurch, then yes. OTR was already disabled, I was messing with it and disabled the plugin *before* I tried using lurch.

I don't understand what you mean by the `libsignal-protocol-c` getting a bump, is that something related to the building process?

Another apology for being clueless for a lot of things.

**Comment by thegreatestminer** [comment]
I found out what you meant by `libsignal-protocol-c`. That was one of the repositories it cloned when running `git submodule update --init --recursive`. I removed anything related to lurch and OTR, cloned the repository again, built it, enabled it, and I still get the same error. Since I have no idea what I'm doing wrong, here's the entire log of me cloning and building `lurch`.

```
# pi @ retropie in ~ [10:26:02] 
$ rm -rf lurch

# pi @ retropie in ~ [10:26:07] 
$ git clone https://github.com/gkdr/lurch && cd lurch
Cloning into 'lurch'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 477 (delta 8), reused 20 (delta 8), pack-reused 457
Receiving objects: 100% (477/477), 158.49 KiB | 0 bytes/s, done.
Resolving deltas: 100% (233/233), done.

# pi @ retropie in ~/lurch on git:master o [10:26:27] 
$ git submodule update --init --recursive
Submodule 'lib/axc' (https://github.com/gkdr/axc) registered for path 'lib/axc'
Submodule 'lib/libomemo' (https://github.com/gkdr/libomemo) registered for path 'lib/libomemo'
Cloning into '/home/pi/lurch/lib/axc'...
Cloning into '/home/pi/lurch/lib/libomemo'...
Submodule path 'lib/axc': checked out '206bf43d3e602598db81a083913144ff7089c88d'
Submodule 'lib/libsignal-protocol-c' (https://github.com/WhisperSystems/libsignal-protocol-c.git) registered for path 'lib/axc/lib/libsignal-protocol-c'
Cloning into '/home/pi/lurch/lib/axc/lib/libsignal-protocol-c'...
Submodule path 'lib/axc/lib/libsignal-protocol-c': checked out '4a137eaf4eb4421949e2e1dde9f11ec7bc07b88f'
Submodule path 'lib/libomemo': checked out '3c8268172829996ec1f1e7b7a12df5c63ceb0ef1'

# pi @ retropie in ~/lurch on git:master o [10:26:38] 
$ make install-home
mkdir -p build
cc -fPIC -std=c11 -Wall -g -Wstrict-overflow -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/include/libpurple -I/usr/include/libxml2 -I./headers/jabber -I./lib/libomemo/src -I./lib/axc/src -I./lib/axc/lib/libsignal-protocol-c/src -D_XOPEN_SOURCE=700 -D_BSD_SOURCE -D_DEFAULT_SOURCE -DPURPLE_PLUGINS -c ./src/lurch.c -o build/lurch.o
make -C "./lib/libomemo" build/libomemo-conversations.a
make[1]: Entering directory '/home/pi/lurch/lib/libomemo'
mkdir -p build
cc -c src/libomemo.c -std=c11 -Wall -Wextra -Wpedantic -Wstrict-overflow -fno-strict-aliasing -funsigned-char -fno-builtin-memset -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -D_THREAD_SAFE -D_REENTRANT   -DOMEMO_XMLNS='"eu.siacs.conversations.axolotl"' -DOMEMO_NS_SEPARATOR='"."' -DOMEMO_NS_NOVERSION -fPIC -o build/libomemo-conversations.o
cc -c src/libomemo_crypto.c -std=c11 -Wall -Wextra -Wpedantic -Wstrict-overflow -fno-strict-aliasing -funsigned-char -fno-builtin-memset -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -D_THREAD_SAFE -D_REENTRANT   -D_XOPEN_SOURCE=700 -D_DEFAULT_SOURCE -fPIC -o build/libomemo_crypto.o
cc -c src/libomemo_storage.c -std=c11 -Wall -Wextra -Wpedantic -Wstrict-overflow -fno-strict-aliasing -funsigned-char -fno-builtin-memset -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -D_THREAD_SAFE -D_REENTRANT   -D_XOPEN_SOURCE=700 -D_DEFAULT_SOURCE -fPIC -o build/libomemo_storage.o
ar rcs build/libomemo-conversations.a build/libomemo-conversations.o build/libomemo_crypto.o build/libomemo_storage.o
make[1]: Leaving directory '/home/pi/lurch/lib/libomemo'
make -C "./lib/axc" build/libaxc-nt.a
make[1]: Entering directory '/home/pi/lurch/lib/axc'
mkdir -p build
cc -fPIC -I./lib/libsignal-protocol-c/src -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include   -std=c11 -g -Wall -Wextra -Wpedantic -Wstrict-overflow -fno-strict-aliasing -funsigned-char -fno-builtin-memset -D_XOPEN_SOURCE=700 -D_BSD_SOURCE -D_POSIX_SOURCE -D_GNU_SOURCE -D_DEFAULT_SOURCE -DNO_THREADS -c src/axc.c -o build/axc-nt.o
src/axc.c:28:16: warning: struct has no members [-Wpedantic]
 typedef struct axc_mutexes {
                ^~~~~~~~~~~
cc -fPIC -I./lib/libsignal-protocol-c/src -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include   -std=c11 -g -Wall -Wextra -Wpedantic -Wstrict-overflow -fno-strict-aliasing -funsigned-char -fno-builtin-memset -D_XOPEN_SOURCE=700 -D_BSD_SOURCE -D_POSIX_SOURCE -D_GNU_SOURCE -D_DEFAULT_SOURCE -c src/axc_crypto.c -o build/axc_crypto.o
cc -fPIC -I./lib/libsignal-protocol-c/src -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include   -std=c11 -g -Wall -Wextra -Wpedantic -Wstrict-overflow -fno-strict-aliasing -funsigned-char -fno-builtin-memset -D_XOPEN_SOURCE=700 -D_BSD_SOURCE -D_POSIX_SOURCE -D_GNU_SOURCE -D_DEFAULT_SOURCE -c src/axc_store.c -o build/axc_store.o
ar rcs build/libaxc-nt.a build/axc-nt.o build/axc_crypto.o build/axc_store.o
make[1]: Leaving directory '/home/pi/lurch/lib/axc'
cd ./lib/axc/lib/libsignal-protocol-c/ && \
   mkdir -p build && \
   cd build && \
   cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS=-fPIC .. \
   && make
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for memset_s
-- Looking for memset_s - not found
-- Performing Test GCC_WARN_SIGN_CONVERSION
-- Performing Test GCC_WARN_SIGN_CONVERSION - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/lurch/lib/axc/lib/libsignal-protocol-c/build
make[1]: Entering directory '/home/pi/lurch/lib/axc/lib/libsignal-protocol-c/build'
make[2]: Entering directory '/home/pi/lurch/lib/axc/lib/libsignal-protocol-c/build'
make[3]: Entering directory '/home/pi/lurch/lib/axc/lib/libsignal-protocol-c/build'
Scanning dependencies of target protobuf-c
make[3]: Leaving directory '/home/pi/lurch/lib/axc/lib/libsignal-protocol-c/build'
make[3]: Entering directory '/home/pi/lurch/lib/axc/lib/libsignal-protocol-c/build'
[  1%] Building C object src/protobuf-c/CMakeFiles/protobuf-c.dir/protobuf-c.c.o
make[3]: Leaving directory '/home/pi/lurch/lib/axc/lib/libsignal-protocol-c/build'
[  1%] Built target protobuf-c
make[3]: Entering directory '/home/pi/lurch/lib/axc/lib/libsignal-protocol-c/build'
Scanning dependencies of target curve25519
make[3]: Leaving directory '/home/pi/lurch/lib/axc/lib/libsignal-protocol-c/build'
make[3]: Entering directory '/home/pi/lurch/lib/axc/lib/libsignal-protocol-c/build'
[  2%] Building C object src/curve25519/CMakeFiles/curve25519.dir/curve25519-donna.c.o
[  3%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/fe_0.c.o
[  4%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/fe_1.c.o
[  5%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/fe_add.c.o
[  6%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/fe_cmov.c.o
[  7%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/fe_copy.c.o
[  8%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/fe_frombytes.c.o
[  9%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/fe_invert.c.o
[ 10%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/fe_isnegative.c.o
[ 11%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/fe_isnonzero.c.o
[ 12%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/fe_mul.c.o
[ 13%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/fe_neg.c.o
[ 14%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/fe_pow22523.c.o
[ 15%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/fe_sq.c.o
[ 16%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/fe_sq2.c.o
[ 17%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/fe_sub.c.o
[ 18%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/fe_tobytes.c.o
[ 19%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/ge_add.c.o
[ 20%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/ge_double_scalarmult.c.o
[ 21%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/ge_frombytes.c.o
[ 22%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/ge_madd.c.o
[ 23%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/ge_msub.c.o
[ 25%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/ge_p1p1_to_p2.c.o
[ 26%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/ge_p1p1_to_p3.c.o
[ 27%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/ge_p2_0.c.o
[ 28%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/ge_p2_dbl.c.o
[ 29%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/ge_p3_0.c.o
[ 30%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/ge_p3_dbl.c.o
[ 31%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/ge_p3_to_cached.c.o
[ 32%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/ge_p3_to_p2.c.o
[ 33%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/ge_p3_tobytes.c.o
[ 34%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/ge_precomp_0.c.o
[ 35%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/ge_scalarmult_base.c.o
[ 36%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/ge_sub.c.o
[ 37%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/ge_tobytes.c.o
[ 38%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/open.c.o
[ 39%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/sc_muladd.c.o
[ 40%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/sc_reduce.c.o
[ 41%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/sign.c.o
[ 42%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/compare.c.o
[ 43%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/curve_sigs.c.o
[ 44%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/elligator.c.o
[ 45%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/fe_isequal.c.o
[ 46%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/fe_isreduced.c.o
[ 47%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/fe_mont_rhs.c.o
[ 48%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/fe_montx_to_edy.c.o
[ 50%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/fe_sqrt.c.o
[ 51%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/ge_isneutral.c.o
[ 52%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/ge_montx_to_p3.c.o
[ 53%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/ge_neg.c.o
[ 54%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/ge_p3_to_montx.c.o
[ 55%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/ge_scalarmult.c.o
[ 56%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/ge_scalarmult_cofactor.c.o
[ 57%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/keygen.c.o
[ 58%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/open_modified.c.o
[ 59%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/sc_clamp.c.o
[ 60%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/sc_cmov.c.o
[ 61%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/sc_neg.c.o
[ 62%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/sign_modified.c.o
[ 63%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/utility.c.o
[ 64%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/generalized/ge_p3_add.c.o
[ 65%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/generalized/gen_eddsa.c.o
[ 66%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/generalized/gen_labelset.c.o
[ 67%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/generalized/gen_veddsa.c.o
[ 68%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/generalized/gen_x.c.o
[ 69%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/generalized/point_isreduced.c.o
[ 70%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/generalized/sc_isreduced.c.o
[ 71%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/xeddsa.c.o
[ 72%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/additions/zeroize.c.o
[ 73%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/nacl_sha512/blocks.c.o
[ 75%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/nacl_sha512/hash.c.o
[ 76%] Building C object src/curve25519/CMakeFiles/curve25519.dir/ed25519/tests/internal_fast_tests.c.o
make[3]: Leaving directory '/home/pi/lurch/lib/axc/lib/libsignal-protocol-c/build'
[ 76%] Built target curve25519
make[3]: Entering directory '/home/pi/lurch/lib/axc/lib/libsignal-protocol-c/build'
Scanning dependencies of target signal-protocol-c
make[3]: Leaving directory '/home/pi/lurch/lib/axc/lib/libsignal-protocol-c/build'
make[3]: Entering directory '/home/pi/lurch/lib/axc/lib/libsignal-protocol-c/build'
[ 77%] Building C object src/CMakeFiles/signal-protocol-c.dir/LocalStorageProtocol.pb-c.c.o
[ 78%] Building C object src/CMakeFiles/signal-protocol-c.dir/WhisperTextProtocol.pb-c.c.o
[ 79%] Building C object src/CMakeFiles/signal-protocol-c.dir/FingerprintProtocol.pb-c.c.o
[ 80%] Building C object src/CMakeFiles/signal-protocol-c.dir/vpool.c.o
[ 81%] Building C object src/CMakeFiles/signal-protocol-c.dir/signal_protocol.c.o
[ 82%] Building C object src/CMakeFiles/signal-protocol-c.dir/curve.c.o
[ 83%] Building C object src/CMakeFiles/signal-protocol-c.dir/hkdf.c.o
[ 84%] Building C object src/CMakeFiles/signal-protocol-c.dir/ratchet.c.o
[ 85%] Building C object src/CMakeFiles/signal-protocol-c.dir/protocol.c.o
[ 86%] Building C object src/CMakeFiles/signal-protocol-c.dir/session_state.c.o
[ 87%] Building C object src/CMakeFiles/signal-protocol-c.dir/session_record.c.o
[ 88%] Building C object src/CMakeFiles/signal-protocol-c.dir/session_pre_key.c.o
[ 89%] Building C object src/CMakeFiles/signal-protocol-c.dir/session_builder.c.o
[ 90%] Building C object src/CMakeFiles/signal-protocol-c.dir/session_cipher.c.o
[ 91%] Building C object src/CMakeFiles/signal-protocol-c.dir/key_helper.c.o
[ 92%] Building C object src/CMakeFiles/signal-protocol-c.dir/sender_key.c.o
[ 93%] Building C object src/CMakeFiles/signal-protocol-c.dir/sender_key_state.c.o
[ 94%] Building C object src/CMakeFiles/signal-protocol-c.dir/sender_key_record.c.o
[ 95%] Building C object src/CMakeFiles/signal-protocol-c.dir/group_session_builder.c.o
[ 96%] Building C object src/CMakeFiles/signal-protocol-c.dir/group_cipher.c.o
[ 97%] Building C object src/CMakeFiles/signal-protocol-c.dir/fingerprint.c.o
[ 98%] Building C object src/CMakeFiles/signal-protocol-c.dir/device_consistency.c.o
[100%] Linking C static library libsignal-protocol-c.a
make[3]: Leaving directory '/home/pi/lurch/lib/axc/lib/libsignal-protocol-c/build'
[100%] Built target signal-protocol-c
make[2]: Leaving directory '/home/pi/lurch/lib/axc/lib/libsignal-protocol-c/build'
make[1]: Leaving directory '/home/pi/lurch/lib/axc/lib/libsignal-protocol-c/build'
cc -fPIC -shared -std=c11 -Wall -g -Wstrict-overflow -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/include/libpurple -I/usr/include/libxml2 -I./headers/jabber -I./lib/libomemo/src -I./lib/axc/src -I./lib/axc/lib/libsignal-protocol-c/src -D_XOPEN_SOURCE=700 -D_BSD_SOURCE -D_DEFAULT_SOURCE -DPURPLE_PLUGINS \
	"./build/lurch.o" ./lib/libomemo/build/libomemo-conversations.a ./lib/axc/build/libaxc-nt.a ./lib/axc/lib/libsignal-protocol-c/build/src/libsignal-protocol-c.a \
	-o build/lurch.so -ldl -lm -lsqlite3 -lmxml -lpthread -lglib-2.0 -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/include/libpurple -L/usr/lib/purple-2 -lxml2 -lgcrypt -ljabber -Wl,-rpath,/usr/lib/purple-2
[ -e "/home/pi/.purple/plugins" ] || \
	install -d -m 755 "/home/pi/.purple/plugins"
install -m 755 "./build/lurch.so" "/home/pi/.purple/plugins/lurch.so"

# pi @ retropie in ~/lurch on git:master o [10:27:46] 
$ cd ..

# pi @ retropie in ~ [10:27:49] 
$ cd .purple/plugins

# pi @ retropie in ~/.purple/plugins [10:27:52] 
$ ls
lurch.so  xmpp-receipts.so
```

**Comment by thegreatestminer** [comment]
Alright, I was able to fix it. I had to enable the plugin, and create a fresh account on the XMPP server using Pidgin. I think doing that made it force regenerate the OMEMO cert/fingerprint, fixing it.

Thanks for developing this plugin! 
![Screenshot from 2019-03-14 10-32-00](https://user-images.githubusercontent.com/19188146/54365293-f6921500-4644-11e9-9bdf-f37c307e1344.png)

**Comment by gkdr** [comment]
>Sorry for the late reply. 

Don't be, as you have noticed I don't manage to get to a computer every day myself. I'll also still gladly answer your questions in the previous posts, if you're still interested.

>Alright, I was able to fix it.

Great! Sounds like the database was in fact corrupted. Maybe deleting it would have helped, too. But that does not seem to matter now anyway.

>Thanks for developing this plugin!

You're welcome! Glad it was useful to someone.

**Comment by EionRobb** [comment]
Perhaps setting some safety `PRAGMA`  options on the sqlite dbs could help with corruption?  The ones I use most frequently are
```
PRAGMA journal_mode=WAL;  -- write-ahead logging
PRAGMA page_size=4096;  -- writes to the disk in block size to help avoid corruption part way through a block
PRAGMA synchronous=OFF; -- buffered disk writes
```
