### ISSUE TITLE
Error sending msg to myself

### ISSUE THREAD

**Issue by Sur3** [gkdr/lurch#47]
Hi i have myself in the contactlist for memos to myself, but with this plugin i get an error sending a msg to myself, it says:
"(09:14:54) There was an error decrypting an OMEMO message addressed to this device. See the debug log for details."
Where to find the debug log?
Sending msg'es to other people works.

**Comment by gkdr** [comment]
Sending a message to yourself breaks forward secrecy as the session will never get advanced, just so you know.
Because of this I might have done something in the code to prevent it, but to be honest I don't quite remember. It should have given a different error though (it just shouldn't encrypt in the first place).

You can find the debug log at _Help -> Debug Window_.

**Comment by Sur3** [comment]
(04:01:06) log: Failed to open log file "/mnt/data/homes/[...]/.purple/logs/[...]@jabber.ccc.de.log" for reading: Datei oder Verzeichnis nicht gefunden
(04:01:06) gtkconv: setting active conversation on toolbar 0x423d530
(04:01:06) prefs: /pidgin/conversations/toolbar/wide changed, scheduling save.
(04:01:06) gtkconv: setting active conversation on toolbar 0x423d530
(04:01:06) GdkPixbuf: gdk_pixbuf_from_pixdata() called on:
(04:01:06) GdkPixbuf: 	Encoding raw
(04:01:06) GdkPixbuf: 	Dimensions: 16 x 16
(04:01:06) GdkPixbuf: 	Rowstride: 64, Length: 1048
(04:01:06) GdkPixbuf: 	Copy pixels == false
(04:01:06) GdkPixbuf: gdk_pixbuf_from_pixdata() called on:
(04:01:06) GdkPixbuf: 	Encoding raw
(04:01:06) GdkPixbuf: 	Dimensions: 16 x 16
(04:01:06) GdkPixbuf: 	Rowstride: 64, Length: 1048
(04:01:06) GdkPixbuf: 	Copy pixels == false
(04:01:06) GdkPixbuf: gdk_pixbuf_from_pixdata() called on:
(04:01:06) GdkPixbuf: 	Encoding raw
(04:01:06) GdkPixbuf: 	Dimensions: 16 x 16
(04:01:06) GdkPixbuf: 	Rowstride: 64, Length: 1048
(04:01:06) GdkPixbuf: 	Copy pixels == false
(04:01:06) GdkPixbuf: gdk_pixbuf_from_pixdata() called on:
(04:01:06) GdkPixbuf: 	Encoding raw
(04:01:06) GdkPixbuf: 	Dimensions: 16 x 16
(04:01:06) GdkPixbuf: 	Rowstride: 64, Length: 1048
(04:01:06) GdkPixbuf: 	Copy pixels == false
(04:01:06) GdkPixbuf: gdk_pixbuf_from_pixdata() called on:
(04:01:06) GdkPixbuf: 	Encoding raw
(04:01:06) GdkPixbuf: 	Dimensions: 16 x 16
(04:01:06) GdkPixbuf: 	Rowstride: 64, Length: 1048
(04:01:06) GdkPixbuf: 	Copy pixels == false
(04:01:06) GLib: Source ID 6880 was not found when attempting to remove it
(04:01:08) util: Writing file prefs.xml to directory /mnt/data/homes/[...]/.purple
(04:01:08) util: Writing file /mnt/data/homes/[...]/.purple/prefs.xml
(04:01:14) jabber: Sending (ssl) ([...]@jabber.ccc.de/theta): <message type='chat' id='purple93e2943a' to='[...]@jabber.ccc.de'><composing xmlns='http://jabber.org/protocol/chatstates'/></message>
(04:01:14) jabber: Recv (ssl)(165): <message to='[...]@jabber.ccc.de' from='[...]@jabber.ccc.de/theta' type='chat' id='purple93e2943a'><composing xmlns='http://jabber.org/protocol/chatstates'/></message>
(04:01:14) psychic: not available, doing nothing
(04:01:18) lurch: retrieved devicelist for [...]@jabber.ccc.de:
<publish node="eu.siacs.conversations.axolotl.devicelist"><item><list
xmlns="eu.siacs.conversations.axolotl"><device id="518306389" /></list></item></publish>
(04:01:18) lurch: retrieved own devicelist:
<publish node="eu.siacs.conversations.axolotl.devicelist"><item><list
xmlns="eu.siacs.conversations.axolotl"><device id="518306389" /></list></item></publish>
(04:01:18) lurch: lurch_msg_encrypt_for_addrs: trying to encrypt key for 1 devices
(04:01:18) lurch: lurch_key_encrypt: encrypting key for [...]@jabber.ccc.de:518306389
(04:01:18) xmlnode: XML parser error for xmlnode 0x44d90a0: Domain 3, code 100, level 1: xmlns: URI eu.siacs.conversations.axolotl is not absolute
(04:01:18) jabber: Sending (ssl) ([...]@jabber.ccc.de/theta): <message type='chat' id='purple93e2943b' to='[...]@jabber.ccc.de'><active xmlns='http://jabber.org/protocol/chatstates'/><encrypted xmlns='eu.siacs.conversations.axolotl'><header sid='518306389'><key rid='518306389'>[...]</key><iv>0SELfcxA7cCy8pVJ2fa4TQ==</iv></header><payload>gTWkERU6L21s9E4E4PMjhKNyVozGJ0Bx9kBELcDQz/fxDX8s</payload></encrypted><encryption xmlns='urn:xmpp:eme:0' namespace='eu.siacs.conversations.axolotl' name='OMEMO'/><store xmlns='urn:xmpp:hints'/></message>
(04:01:18) jabber: Sending (ssl) ([...]@jabber.ccc.de/theta): <message type='chat' id='purple93e2943c' to='[...]@jabber.ccc.de'><active xmlns='http://jabber.org/protocol/chatstates'/></message>
(04:01:18) jabber: Recv (ssl)(751): <message to='[...]@jabber.ccc.de' from='[...]@jabber.ccc.de/theta' type='chat' id='purple93e2943b'><active xmlns='http://jabber.org/protocol/chatstates'/><encrypted xmlns='eu.siacs.conversations.axolotl'><header sid='518306389'><key rid='518306389'>[...]</key><iv>0SELfcxA7cCy8pVJ2fa4TQ==</iv></header><payload>gTWkERU6L21s9E4E4PMjhKNyVozGJ0Bx9kBELcDQz/fxDX8s</payload></encrypted><encryption xmlns='urn:xmpp:eme:0' namespace='eu.siacs.conversations.axolotl' name='OMEMO'/><store xmlns='urn:xmpp:hints'/></message>
(04:01:18) jabber: XML parser error for JabberStream 0x41ecef0: Domain 3, code 100, level 1: xmlns: URI eu.siacs.conversations.axolotl is not absolute
(04:01:18) lurch: lurch_message_decrypt: failed to prekey msg (-1005)
(04:01:18) jabber: Recv (ssl)(162): <message to='[...]@jabber.ccc.de' from='[...]@jabber.ccc.de/theta' type='chat' id='purple93e2943c'><active xmlns='http://jabber.org/protocol/chatstates'/></message>
(04:01:48) jabber: Sending (ssl) ([...]@jabber.ccc.de/theta): <iq type='get' id='purple93e2943d'><ping xmlns='urn:xmpp:ping'/></iq>
(04:01:48) jabber: Recv (ssl)(95): <iq to='[...]@jabber.ccc.de/theta' from='[...]@jabber.ccc.de' type='result' id='purple93e2943d'/>

**Comment by Sur3** [comment]
hmm github removes all the angle brackets, but i think the important lines are anyway:
"(04:01:18) jabber: XML parser error for JabberStream 0x41ecef0: Domain 3, code 100, level 1: xmlns: URI eu.siacs.conversations.axolotl is not absolute
(04:01:18) lurch: lurch_message_decrypt: failed to prekey msg (-1005)"

**Comment by gkdr** [comment]
You can use triple ` to make a 'code' field which ignores formatting. I edited your comment to include them.

Okay, the problem here is that `libsignal-protocol-c` does not support having sessions with yourself (and you seem to have only one OMEMO device).

For now, since you don't have other devices anyway (according to the devicelist), you can fix this by adding yourself to the blacklist by typing `/lurch blacklist add` in the conversation window. This disables encryption.

I will remove that error (since encrypting it for your other devices would still work), I simply did not anticipate sending messages to yourself.
Then it won't be sent in plaintext, and you have it in your log, but there will be no device that can read it.

**Comment by Sur3** [comment]
well normally i can also be logged in to the same xmpp account on different devices, and msg send are then shared, but with this problem it doesnt send at all but shows the above error, when using ```/lurch blacklist add``` it sends to the other devs as well, but msg send are not encrypted, but i can still receive encrypted msges then:
```(02:35:02) Received encrypted message in blacklisted conversation.
(02:35:02) [...]@jabber.ccc.de/theta: test```
can i also not just block by xmpp-address but include the ressource in the blacklist something like ```/lurch blacklist add name@server.de/this``` ?

**Comment by Sur3** [comment]
"Then it won't be sent in plaintext, and you have it in your log, but there will be no device that can read it."
How do you mean that, you mean packets to myself device id are not send anyway but handled internally by purple?
Then it would probably be the best solution to blacklist self device id by default if the packets to that device aren't send anyway.

**Comment by gkdr** [comment]
>well normally i can also be logged in to the same xmpp account on different devices, and msg send are then shared, but with this problem it does send but also shows the above error on every msg

I realize this is annoying, but I think it is a better design decision than to fail silently. With pure _libpurple_ (i.e. no GUI code) I don't really have another possibility to display it.

>can i instead not just block by xmpp-address but include the ressource in the blacklist something like /lurch blacklist add name@server.de/this or blacklist by device id?

Not right now, but I guess I can consider it for the future. Maybe it would not be necessary when I implement per-device trust anyway.

>I also found a related error, when there are two clients with lurch and only one of the clients adds the other in blacklist, a fallback to OTR doesnt really work, because OTR msg'es are not parsed by the OTR plugin then. So both lurch clients must blacklist the other for OTR to work instead.

It is not possible to detect whether a client that can handle _OMEMO_ actually has turned it on for a conversation. If you tell me which client has such an "OTR fallback", I could ask the developer about it. I don't know why the OTR plugin shouldn't work, but it could be as easy as changing the handler priority.

>"Then it won't be sent in plaintext, and you have it in your log, but there will be no device that can read it."
How do you mean that, you mean packets to myself device id are not send anyway but handled internally by purple?

The message will be sent encrypted, but there will be no `<key>` element, so it's not possible to decrypt it. This is why it will be ignored when you receive it, but it will show up in your log because you wrote it. Since I already exclude the own device when getting the own devicelist for encryption, implementing it this way will be easier than adding logic to drop packages sent to yourself (and out of scope of this plugin).

>Btw what would happen if there is a device id collision between two different devices, the probability is probably low, but i just wonder... ^^"

I think it's not in the currently published standard, but the new draft says to simply try decrypting all messages that have your ID. This works because decryption will fail for the other device with the same ID anyway.

**Comment by Sur3** [comment]
> Maybe it would not be necessary when I implement per-device trust anyway.

I'm looking forward to that then. 👍 
Probably we can then put an additional drop/ignore option for an device in as a possibility to get rid of the error messages upon receiving from own device or i have to direct this upstream...

> The message will be sent encrypted, but there will be no <key> element, so it's not possible to decrypt it. This is why it will be ignored when you receive it, but it will show up in your log because you wrote it. Since I already exclude the own device when getting the own devicelist for encryption, implementing it this way will be easier than adding logic to drop packages sent to yourself (and out of scope of this plugin).

That makes sense, I tried to set the ignore in pidgin itself to get rid of the error msg, but it redirects to the server, therefore an ignore is then set globally instead of per device and no msg'es are then received at all, i'll probably direct this need for local droping/blocking upstream.

> It is not possible to detect whether a client that can handle OMEMO actually has turned it on for a conversation.

But somehow it detects capability on first connection, isn't there some kind of key invalidation so the client tries to redetect and then falls back to no-omemo when it sees its gone..
> If you tell me which client has such an "OTR fallback", I could ask the developer about it. I don't know why the OTR plugin shouldn't work, but it could be as easy as changing the handler priority.

Ok as OTR seemes to have a more sophisticated capability of detecting OTR-Clients that probably makes sense then to change the prio, but idk if that works better, would have to test that is think. I dont know of a specific client aside from libpurple that can do both protocols.

**Comment by Sur3** [comment]
Ok i created an upstream bug now: https://developer.pidgin.im/ticket/17198

**Comment by gkdr** [comment]
>But somehow it detects capability on first connection, isn't there some kind of key invalidation so the client tries to redetect and then falls back to no-omemo when it sees its gone..

You can deactivate the device completely by removing it from the devicelist (this is what the `uninstall` command does). This does not work for individual conversations.

By the way, are you on Windows or can you compile it yourself? I could fix it quick and push it on a dev branch, but I don't want to make a new release just for this feature, and don't have time to do much else right now.

(I'll reopen this issue so I don't forget to do it.)

**Comment by Sur3** [comment]
I'm on Gentoo Linux i can compile myself.

**Comment by gkdr** [comment]
Okay, check out the dev branch, that should fix it for you :D

**Comment by Sur3** [comment]
I think i understand the patch but just to be clear, does this patch remove sending to the own device at all or is it just removed from lurch and sent in cleartext instead?
Well the error-message is gone, i still see the "[...] is typing.." message though inside my own window but that is not really a problem.
But there is a newline on the other-device upon received lines now, so when sending multiple messages they are seperated by empty lines on the recipients side if they dont contain a linebreak themself. o.O

**Comment by Sur3** [comment]
Well that is funny, sending to an other jabber-id also produces these empty lines if i'm logged in to my own jabber-id on two devices, but if i'm only logged in with one device/resource then there are no empty lines seperating the messages.

**Comment by gkdr** [comment]
The patch just skips looking for the "recipient"'s devices if the recipient is you, so the symmetric encryption key is only encrypted for your own devices, minus the sending device itself.
If you have no other devices, it is going to be an encrypted message which is not decryptable because there is no encrypted symmetric encryption key contained in the message (you can confirm this in the debug log, the message has no `<key>` element).

I'm really not sure what could be producing the newlines though. It definitely didn't happen before?

**Comment by Sur3** [comment]
I just looked into my logfiles seemes it also happend before, think i didn't recognize it because of the error-messages. xD

**Comment by Sur3** [comment]
Yes just downgraded they happen in normal 0.6.5 too.

**Comment by gkdr** [comment]
Okay, since it has nothing to do with this patch, can you open a new issue? This will be auto-closed once it gets merged into the master.

An example would be nice too, I don't really get it. Do you maybe have a plugin that groups messages together? Because two messages should usually stay two messages, and not get appended to each other.

**Comment by Sur3** [comment]
I have an other related issue to sending msg'es to myself, when i'm connected on two devices and they have the same status level (eg away) then msg are send two both resources, but when one resource is available and the other is away the msg is only send to the available resource, even if it's the own resource.
I think the own resource should always have lowest priority there, so msg are always send to an other resource if available. Are these priorities handled in lurch or is it out of scope?

**Comment by gkdr** [comment]
I think that is server implementation dependent, so way out of scope.
If are okay with copying all messages to all resources, you could try my [message carbons plugin](https://github.com/gkdr/carbons).
